### ISSUE TITLE
App freezes if it doesn't have permission to access camera

### ISSUE THREAD

**Issue by tore-espressif** [espressif/esp-rainmaker-android#10]
Hello,

This app freezes if it is not given permission to access phone's camera.

Granting the permission through Android system settings fixed the problem, but it should be handled in the app, saying something like 'This app needs access to camera for correct operation'.

Thanks!

**Comment by khushbushah2302** [comment]
Hi @tore-espressif, thanks for your feedback. We will improve user experience for camera permission.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been addressed.
