### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vishnu2201** [espressif/esp-rainmaker-android#11]
<img width="514" alt="Screenshot 2021-05-26 at 12 30 02 PM" src="https://user-images.githubusercontent.com/30022347/119616335-1bd25e80-be1e-11eb-9d0c-886f9a262bae.png">
How to remove this error

**Comment by khushbushah2302** [comment]
Hi @Vishnu2201 , 
Please do git clone command to get android project (instead of downloading it).

**Comment by shahpiyushv** [comment]
Closing this issue since it has been answered.
