### ISSUE TITLE
Params in expanded view refresh too slowly

### ISSUE THREAD

**Issue by xhivo97** [espressif/esp-rainmaker-android#15]
I have made a device that has a read only parameter with a `esp.ui.text` element and everything works as it should except for the slow refresh rate on the Android app. If I refresh the page manually it updates the status otherwise it takes a good couple of seconds.

For context the device is a garage door opener and the status param just keeps track of the door position and if it's moving.

This is how I want it to work:
1. User taps button
2. ESP32 Sends new garage door state
3. ESP Rainmaker updates the UI element in a timely manner

It'd be nice to have the option for some widgets to refresh more often, at least in their expanded view.

Is there an existing solution to this or is some modification necessary.

**Comment by shahpiyushv** [comment]
@xhivo97 , we indeed have support for reporting parameter updates to the phone apps in real time. The same is even being used to update the home screen of the app instantaneously. Even when a user is on the params screen, the app gets the values in real time, but they haven't yet been used to update the UI elements. This will be handled soon.

**Comment by khushbushah2302** [comment]
Hi @xhivo97 ,

Fixed the issue in latest app (version 2.6.1 - 5ecc246).
Commit id : 5ecc246ac1cecc35e2f7ddfae446117f1377d85c
