### ISSUE TITLE
[HELP] Cannot log-in, possible Amazon Cognito setup issue

### ISSUE THREAD

**Issue by meltdown03** [espressif/esp-rainmaker-android#2]
I followed the README file and setup an Amazon Cognito User Pool. (I used the default options for it.) I also created the App Client so I have the 3 required pieces of information according to the README. I successfully built the Android App in AndroidStudio and loaded it onto my phone. I get this error when attempting to login:

**Sign-in failed**
Unable to verify secret hash for client <the app client_id from Cognito>

![Screenshot_20201110-182702_ESP RainMaker](https://user-images.githubusercontent.com/6166536/98750536-d8ce0380-2383-11eb-9156-449c34358be7.jpg)

Can you please provide more info on the Amazon Cognito side of the configuration? Also, will I be able to login with my normal email/password or am I required to use a new one that is also in Cognito?

**Comment by khushbushah2302** [comment]
Hi @meltdown03 ,

Try with below configuration.
```
"aws_region" - ""
"user_pool_id" - "us-east-1_kWz4M6MfD"
"client_id" - "60i6kac5f9rjuetqnq5mnmaqv6"
```

**Comment by meltdown03** [comment]
> Hi @meltdown03 ,
> 
> Try with below configuration.
> 
> ```
> "aws_region" --> ""
> "user_pool_id" --> "us-east-1_kWz4M6MfD"
> "client_id" --> "60i6kac5f9rjuetqnq5mnmaqv6"
> ```

I basically had mine like that except I was in the `us-west-2` region so I had that set and my user_pool_id started with it. Do you have to create a user or signup through the app once the pool is created?

**Comment by meltdown03** [comment]
Your config **did** let me log in though. I must have something set up wrong with Amazon Cognito. Could you tell me what you changed from the default values when you set up your pool? Like URLs, App Client, and Authorization settings.

**Comment by meltdown03** [comment]
I think I got a bit further... I recreated the app client and unchecked "Generate secret key". I no longer get the the error as in the OP. I now get "Incorrect username or password" or "Password attempts exceeded" if I try to many times.

**Comment by meltdown03** [comment]
I recreated the app client and unchecked "Generate secret key". I no longer get the the error as in the OP. I now get "Incorrect username or password". If I signup a new user, that user works. It's not forwarding or linking to the ESP-Rainmakers user database, just making it's own. How did you @khushbushah2302  get it setup in Cognito to do that?

**Comment by meltdown03** [comment]
I'm assuming you gave me the pool_id and app_client_id that all users use so I'm closing this issue. I now realize that I can make my own User Pool if I want.

**Comment by shahpiyushv** [comment]
@meltdown03 , I think there is some confusion here. The phone apps and CLI for ESP RainMaker will work with only one specific Cognito User Pool we have created in our RainMaker backend (and which @khushbushah2302 has mentioned above). Any other cognito user pool will not work. I may be wrong in my own understanding of the issue, so do let me know accordingly.

**Comment by meltdown03** [comment]
> @meltdown03 , I think there is some confusion here. The phone apps and CLI for ESP RainMaker will work with only one specific Cognito User Pool we have created in our RainMaker backend (and which @khushbushah2302 has mentioned above). Any other cognito user pool will not work. I may be wrong in my own understanding of the issue, so do let me know accordingly.

Yes, that _is_ how it works as I understand. You can make your own User Pool if you want, otherwise, use the info from @khushbushah2302 to use the normal pool from Espressif.
