### ISSUE TITLE
Device Automation

### ISSUE THREAD

**Issue by chetan87-kamble** [espressif/esp-rainmaker-android#24]
Hello,

I want to develop Device Automation as per iOS project. When we will receive Device Automation Support in Android also?

Regards,
Chetan Kamble

**Comment by khushbushah2302** [comment]
Hi @chetan87-kamble ,
We are working on it. It will be available in Android too.

**Comment by chetan87-kamble** [comment]
> Hi @chetan87-kamble , We are working on it. Device automation feature will be available in Android too.

Hi @khushbushah2302,
Thanks for your reply. Can you please confirm when it will be available in Android? I mean in coming week or month or 2 months. If it is confirmed then it will by easy to plan that activity. Thank you!
Regards,
Chetan Kamble

**Comment by jacek12345** [comment]
Also waiting for this information...

**Comment by khushbushah2302** [comment]
Device automation feature will be available in one month.

**Comment by chetan87-kamble** [comment]
> Device automation feature will be available in one month.

Hi @khushbushah2302,
Thank you for your update. I will plan my activity accordingly. Thank you!

**Comment by jacek12345** [comment]
How about update?

**Comment by jacek12345** [comment]
@khushbushah2302 Can you tell us how the app update is going?

**Comment by khushbushah2302** [comment]
Hi @jacek12345 , @chetan87-kamble ,
Device automation feature is available now.
