### ISSUE TITLE
Schedule timezones 

### ISSUE THREAD

**Issue by brain113** [espressif/esp-rainmaker-android#3]
Hi,
When you enter a schedule time you usually expect it in local timezone. But the device actually interpret it in the GMT timezone.
At he moment you have to manually convert desirable time to to GTM timezone to make schedules work as expected.

Is it possible to let the Rainmaker App convert schedule time to GMT when the app set the schedule to a device, and convert the time back to local time when the app reads the schedule from a device?

**Comment by shahpiyushv** [comment]
@brain113 , you actually need to set the timezone on the device. You can check [here](https://rainmaker.espressif.com/docs/time-service.html#time-zone) for the details. However, it seems that this information is getting missed and we will check on how to make it much more visible. If you have any suggestions, do let us know.

**Comment by khushbushah2302** [comment]
Hi @brain113 ,
Time zone configuration is now supported. 
You can update your node to support any time zone provided in the dropdown list.

Thanks.

**Comment by brain113** [comment]
Hi @khushbushah2302 
Thank you for letting me know! I will try this on this week.

**Comment by gotfredsen** [comment]
Can the TimeZone be set after the Rainmaker has been started (after provisioning and once connected to the Internet)? That way I can check using an Internet API what my timezone is.

**Comment by khushbushah2302** [comment]
Hi @gotfredsen , Yes. TimeZone can be set after provisioning. TimeZone setting is available in Node details screen.

**Comment by shahpiyushv** [comment]
Closing this issue since it has been answered.
