### ISSUE TITLE
Can provsioning with QR code but can't manually

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker-android#33]
It looks like some permissions issue. Phone didn't ask about permision when used manually BLE (and didn't find device). After trying first time with QR, it asked about permisions two times (two different questions that I agreed). It is Android 10. It doesn't work in Android 11 also, but works in 12.

**Comment by jacek12345** [comment]
can you confirm?

**Comment by khushbushah2302** [comment]
Hi @jacek12345 , manual BLE provisioning is failing due to permission issue. It is fixed now and will be available soon.

**Comment by khushbushah2302** [comment]
Hi @jacek12345 , can you please check with latest app ?

**Comment by jacek12345** [comment]
Thank You, now it works with v.2.8.1.
