### ISSUE TITLE
App Login

### ISSUE THREAD

**Issue by sharmajiji** [espressif/esp-rainmaker-android#35]
In esp rainmaker app login is not working i have tried from several devices and mail ids to login but it show failed to login.

**Comment by shahpiyushv** [comment]
There were some certificate issues with the app which were fixed in version 2.10.1. Account creation/login has no relation to bluetooth. Probably things worked on the tablet because it may have downloaded the latest app.

**Comment by FernandoGarcia** [comment]
Makes sense. Thanks!

**Comment by khushbushah2302** [comment]
Hi @sharmajiji , the issue is fixed in latest 2.10.1 version app.
