### ISSUE TITLE
Matter

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-rainmaker-android#42]
Does the integration with matter still not work?

Downloading the app from the google play store works, filling out this no...

I noticed that the version on the store is later 3.2.0, this one has remained at 3.0.0, will it be updated? Thank you

**Comment by KhushbuShah25** [comment]
Hi @stefano055415 ,
3.2.0 code is available now.
Matter support is disabled by default in app source code.
To enable it, make `matterBuild` variable as true at [this line](https://github.com/espressif/esp-rainmaker-android/blob/b9dd60242cae518f8debb68181ddae799cd4fcb2/app/build.gradle#L45). And add `isMatterSupported=true` in local.properties file.

**Comment by stefano055415** [comment]
Hi @KhushbuShah25 ,

Perfect thanks now it works.

I just have one problem with my implementation.
Everything seems to work fine until the SetNocChain function

It appears that for some reason it is not aligned to the correct state.

I'll try to explain the steps I take

I receive the CSR from the device on the onNOCCainGenerationNeeded function, I ask for the NOC generation, I receive the NOC, I call the onNOCCainGeneration function passing it the correct parameters rootCA, intermediateCA, noc (just received) and ipkEpochKey

But I get this error:

Unable to set SetNocChain for device: src/controller/java/AndroidOperationalCredentialsIssuer.cpp:304: CHIP error 0x00000003: Incorrect state
