### ISSUE TITLE
All devices appear offline when attempting to control them

### ISSUE THREAD

**Issue by Maldus512** [espressif/esp-rainmaker-android#44]
Since the last Android update all devices associated with my user appear to be offline when inspected.
In the main page with the device list the online status is correct, but when I click on them the device page displays the message "Offline at XX:XX" at the top and prevents me from writing the device's parameters, despite being able to read them.

**Comment by KhushbuShah25** [comment]
Thanks for reporting the issue. 
The issue has been fixed in latest app.

**Comment by Maldus512** [comment]
I can confirm this, thank you for the assistance.
