### ISSUE TITLE
Getting error while building this app locally

### ISSUE THREAD

**Issue by Kartikgupta1502** [espressif/esp-rainmaker-android#46]
Could not determine the dependencies of task ':app:extractIncludeDebugProto'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.warkiz.tickseekbar:tickseekbar:0.1.4.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Kartikgupta1502** [comment]
@KhushbuShah25 any idea how to resolve this?

**Comment by KhushbuShah25** [comment]
Hi @Kartikgupta1502 , will check and update soon.

**Comment by ShanmugaCA** [comment]
@KhushbuShah25 and @Kartikgupta1502 :
Getting the same "tickseekbar" error... any help is appreciated!

Thanks in advance!

**Comment by KhushbuShah25** [comment]
The issue is resolved now. The build is in testing. Will update GitHub code soon.

**Comment by ramupal2603** [comment]
@KhushbuShah25 by how soon we can expect the updated code on GitHub, or if there's a quick fix we can apply in the meantime.
Appreciate your help!
 

> The issue is fixed now. The build is in testing. Will update GitHub code soon.

**Comment by KhushbuShah25** [comment]
Hi @ramupal2603 , fixed build issue in recent commit.
