### ISSUE TITLE
Error Connecting ESP32S2 to rainmaker

### ISSUE THREAD

**Issue by Shravani100** [espressif/esp-rainmaker-android#5]
Hi,

I am trying to connect to ESP32-S2 WROOM board to esp rainmaker app on android device I am using the following esp rainmaker project 
https://github.com/espressif/esp-rainmaker.git
I am using switch example.
I have successfully compiled and flashed the code to the device. Also I get the the QR code. My device is successfully connected to Wi-Fi. While Configuring the user node association I get error as Failed to configure node association,
I am attaching the screenshots for both app side as well as console.

Any help would be highly appreciated😊

![screenshot_console](https://user-images.githubusercontent.com/75830255/101884613-fed30780-3bbe-11eb-8d11-14423d443f43.jpeg)
![screenshot_app](https://user-images.githubusercontent.com/75830255/101884620-009ccb00-3bbf-11eb-956e-5df25b1850d5.jpeg)

**Comment by khushbushah2302** [comment]
Hi @Shravani100 ,
3rd step in provisioning requires internet to call cloud API.
I think internet may not available or too slow.

**Comment by Shravani100** [comment]
Hi @khushbushah2302 ,
Thank you so much for the reply😊. I will look into that

**Comment by khushbushah2302** [comment]
@Shravani100 ,
Can you share android side logs if you are facing this issue continuously ?

**Comment by Shravani100** [comment]
> @Shravani100 ,
> Can you share android side logs if you are facing this issue multiple times ?

@khushbushah2302 

please check the attached
[Android_log.txt](https://github.com/espressif/esp-rainmaker-android/files/5688646/Android_log.txt)
 log

**Comment by khushbushah2302** [comment]
Hi @Shravani100 ,

Thanks for sharing logs.
From logs, it seems user authentication issue on which currently we are working.
I will let you know once it is fixed.
Please try to logout and login again for now.

And are you using PlayStore app or compiled app from source ?

**Comment by Shravani100** [comment]
hi @khushbushah2302 

I am using playstore app and android version is 7

**Comment by Shravani100** [comment]
hi @khushbushah2302 

I am again facing the issue with the configuring user node association with esp-rainmaker app from the play store.Last time I have changed the android version to 10 and it started working.Now I am using the same android version 10 still I am facing the same issue repeatedly. 
Any solution to this?

**Comment by khushbushah2302** [comment]
Hi @Shravani100 ,

Sorry for late. This issue has been fixed in latest app.
Please check new app.

Thanks.
