### ISSUE TITLE
No string for proof_of_possesion

### ISSUE THREAD

**Issue by CodorStelian** [espressif/esp-rainmaker-android#6]
https://github.com/espressif/esp-rainmaker-android/blob/ebddf8e284bf8c5343f2a2617c16c6697346e24e/app/src/main/java/com/espressif/ui/activities/ProofOfPossessionActivity.java#L79

Can you check this? I think this resource string does not exist in values/strings.xml

**Comment by khushbushah2302** [comment]
Hi @CodorStelian ,

You are right. this resource string does not exist in values/strings.xml.
It is present in [app/build.gradle file](https://github.com/espressif/esp-rainmaker-android/blob/ebddf8e284bf8c5343f2a2617c16c6697346e24e/app/build.gradle#L45). "proof_of_possesion" is configurable so you can modify it as per your requirement. 
Resource (R.string.proof_of_possesion) will be generated when you build the project.

Thanks.

**Comment by CodorStelian** [comment]
I understand. Thanks for the response.
Have a beautiful day!
