### ISSUE TITLE
[ESP Local control] does not seem to work with mobile hotspot local area network.

### ISSUE THREAD

**Issue by noobGB** [espressif/esp-rainmaker-android#7]
Hi Team,  I have created a wifi hotspot on my Moto G5S plus(Android 8.1.1) and configured ESP32 for local control. Now my ESP32 node and rainmaker app on another phone(Moto G6, android V9.1) connected to same hotspot network. Then I turned off the data on Moto G5S plus and kept the wifi hotspot ON, ideally now the phone app should show [Reachable on WLAN] as there is no internet available but LAN is available, but it does not, please put some light on this if I am making some mistake here.

**Comment by shahpiyushv** [comment]
@noobGB , do you see the "Reachable on WLAN" message while the mobile data on the hotspot is still turned on? Local control is supposed to work irrespective of whether or not the Internet is available. If you do not see that message at all, can you double check if the local control feature is indeed enabled in your firmware? You need to set `CONFIG_ESP_RMAKER_LOCAL_CTRL_ENABLE=y` to enable it.

**Comment by ameyinamdar** [comment]
@noobGB Also, please note that sometimes the hotspots don't allow communication between two clients. It will be better if the test is run with a full fledged access point instead of the hotspot.

**Comment by noobGB** [comment]
@shahpiyushv , I have doubled check the "CONFIG_ESP_RMAKER_LOCAL_CTRL_ENABLE=y" configuration and it is fine. I do not see the "Reachable on WLAN" message in none of the scenario when the internet is OFF or ON.

@ameyinamdar , I wanted to test mobile hotspot first as it is the easiest way to create LAN when full fledged access point router not available, please check this issue as non-technical customers wont understand the difference between hotspot and full fledge router while connecting their smart device. Now I will test this functionality on some DLink or other router and will get back to you.

**Comment by noobGB** [comment]
@shahpiyushv , @ameyinamdar , I have just tried JIOFI network, now I can see [Reachable on WLAN] on MOTO G5S PLUS device but this [Reachable on WLAN] is not visible on MOTO G6 for same account and LED light node. It may be a UI issue on Moto G6. Please check.

**Comment by shahpiyushv** [comment]
@noobGB , I don't think it is a UI issue. If you control the device from your phone app, the device console shows prints like these if it is indeed reachable on the local WLAN network:

```
I (129636) app_main: Received write request via : Local
```

Else it shows

```
I (58069) app_main: Received write request via : Cloud
```
Can you check what you see?

Meanwhile, you can install the [Service Browser](https://play.google.com/store/apps/details?id=com.druk.servicebrowser&hl=en_US&gl=US) app on your phone and see if it can search for the `_esp_local_control._tcp` mDNS service.

**Comment by noobGB** [comment]
@shahpiyushv , you are right, it is not an UI issue as [Reachable on WLAN] becomes visible on Moto G6 after sometime to jiofi connection or sometime it does not show at all, so it is definitely access point issue.

**Comment by shahpiyushv** [comment]
Closing this issue as it seems to have been addressed. Please feel free to reopen if required.

**Comment by gsrathore97** [comment]
We learn from this a lot but we still didn't get any clue on How to use local control ESP Rainmaker. If anyone has any tutorial video or blog article please share.
