### ISSUE TITLE
Device state change initiated from hardware does not reflect instantaneously on app, needs app refresh most of the time.

### ISSUE THREAD

**Issue by noobGB** [espressif/esp-rainmaker-android#8]
Hi Team, 

Hardware initiated state change does not reflect instantaneously on app over cloud or local connection, needs manual app refresh to check the changes. This is a big issue from non technical customer point of view, they will question the hardware and app sync property of the device. Before ESP rainmaker, I was using BLYNK IOT platform for product design, their sync mechanism is almost real time without any app page refresh. Please let me know If I should make some configuration changes to sort this issue.

Another scenario :
I have logged in two mobiles phones from same user account, if I make state change from one mobile app then I need to refresh other mobile app page to get latest device states.

**Comment by shahpiyushv** [comment]
@noobGB , on the home page of the phone app, you would indeed need a manual refresh. Currently, we do not have any notification mechanism from cloud side and auto refresh on this page will keep fetching lots of data from the cloud for each node unnecessarily. On the device details page, an auto-refresh happens every 5 seconds, which we believe is a decent enough time. We can increase this frequency to say once every 3 seconds if device is on local network. Going ahead, once we have a notification mechanism in place, the updates could happen faster as the phone would not have to keep querying, but will instead get the updates asynchronously.

**Comment by noobGB** [comment]
@shahpiyushv , Thank you for the clarification, indeed notification mechanism from cloud would make app device state update smoother and faster. Refresh frequency change to 3 seconds for local network seems to be a good idea for the time being.

**Comment by kebiromar** [comment]
hello, @shahpiyushv  i think the most simple solution is to create an mqtt topic per app user that is used by the devices to inform the phone app that one of the user nodes is updated and then the app can refresh her data using the rest-api.
auto-refresh every 5 seconds is is data consuming solution and not efficient.

**Comment by khushbushah2302** [comment]
Hi @noobGB , notification feature is added now. Please take update.

**Comment by sahal-bit** [comment]
please how can add bottom switch to esp rainmaker? like to open my gate and close it.

**Comment by shahpiyushv** [comment]
@sahal-bit , the requirement is not clear here, but more importantly, this does not seem relevant under this specific issue. Please file a new issue with appropriate details.
